---

- name: build pact db docker container
  shell: docker-compose build
  args:
    chdir: /vagrant/movie-example/tool

- name: run pact broker docker and db
  shell: docker-compose up -d
  args:
    chdir: /vagrant/movie-example/tool