---
- name: build all jar
  shell: sh ./buildAll.sh
  args:
    chdir: /vagrant/movie-example

- name: build example docker container
  shell: docker-compose build
  args:
    chdir: /vagrant/movie-example

- name: run docker
  shell: docker-compose up -d
  args:
    chdir: /vagrant/movie-example