---
- hosts: server
  tasks:
    - name: install curl
      apt:
        name: curl
        state: present

    - name: setup java ppa
      shell: |
        echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/webupd8team-java.list
        echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | sudo tee -a /etc/apt/sources.list.d/webupd8team-java.list
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
        echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
        echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
        export DEBIAN_FRONTEND=noninteractive

    - name: install jdk
      apt:
        update_cache: true
        name: oracle-java8-installer
        state: present

    - name: install jdk
      apt:
        name: oracle-java8-set-default
        state: present
        
- hosts: server
  roles:
    #  - williamyeh.oracle-java
     - angstwad.docker_ubuntu
     - support
     - mgp
     - movie
     - test
  vars:
    java_version: 8