---
- hosts: server
  tasks:
    - name: install curl
      apt:
        name: curl
        state: present

- hosts: server
  roles:
     - williamyeh.oracle-java
     - angstwad.docker_ubuntu
     - support
     - mgp
     - movie
     - test
  vars:
    java_version: 8