---
- hosts: server
  tasks:
    - name: install curl
      apt:
        name: curl
        state: present

    - name: setup nodejs
      shell: curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    
    - name: install nodejs
      apt:
        name: nodejs
        state: present
        
- hosts: server
  roles:
     - williamyeh.oracle-java
     - angstwad.docker_ubuntu
     - support
     - mgp
     - movie
     - test
  vars:
    java_version: 8