---
- hosts: server
  roles:
     - williamyeh.oracle-java
     - role: angstwad.docker_ubuntu
       pip_install_pip: false
       pip_install_setuptools: false
     - support
     - mgp
     - movie
  vars:
    java_version: 8