---
- hosts: server
  tasks:
    - name: install curl
      apt:
        name: curl
        state: present

- hosts: server
  roles:
     - williamyeh.oracle-java
     - role: angstwad.docker_ubuntu
       pip_install_pip: false
       pip_install_setuptools: false
     - support
     - mgp
     - movie
     - test
  vars:
    java_version: 8